-- ACAD_CRSE_LIST: view of all courses taken by each student, with grades

CREATE OR REPLACE FORCE VIEW GG_OCAS_SYNC.ACAD_CRSE_LIST
(
    PIDM,
    MAJOR,
    MAJOR_DESC,
    TERM_CODE,
    SUBJ_CODE,
    CRSE_NUMB,
    COURSE_TITLE,
    GRADE,
    CREDIT_HOURS,
    CREDIT_HOURS_EARN,
    QUALITY,
    INCLUDE_IN_GPA,
    NUMERIC_VALUE
)
AS
      SELECT SGBSTDN_PIDM,
             SGBSTDN_MAJR_CODE_1,
             STVMAJR_DESC,
             SHRTCKN_TERM_CODE,
             SHRTCKN_SUBJ_CODE,
             SHRTCKN_CRSE_NUMB,
             COALESCE (SHRTCKN_LONG_COURSE_TITLE, SHRTCKN_CRSE_TITLE, 'Title Not Available'),
             MAX (SHRTCKG_GRDE_CODE_FINAL) KEEP (DENSE_RANK LAST ORDER BY SHRTCKG_SEQ_NO),
             MAX (SHRTCKG_CREDIT_HOURS) KEEP (DENSE_RANK LAST ORDER BY SHRTCKG_SEQ_NO),
             CASE MAX (SHRGRDE_COMPLETED_IND)
                      KEEP (DENSE_RANK LAST ORDER BY SHRGRDE_TERM_CODE_EFFECTIVE)
                 WHEN 'Y'
                 THEN
                     MAX (SHRTCKG_CREDIT_HOURS) KEEP (DENSE_RANK LAST ORDER BY SHRTCKG_SEQ_NO)
                 ELSE
                     0
             END,
             MAX (SHRGRDE_QUALITY_POINTS)
                 KEEP (DENSE_RANK LAST ORDER BY SHRGRDE_TERM_CODE_EFFECTIVE),
             MAX (SHRGRDE_GPA_IND) KEEP (DENSE_RANK LAST ORDER BY SHRGRDE_TERM_CODE_EFFECTIVE),
             MAX (SHRGRDE_NUMERIC_VALUE)
                 KEEP (DENSE_RANK LAST ORDER BY SHRGRDE_TERM_CODE_EFFECTIVE)
        FROM SATURN.SGBSTDN SA
             INNER JOIN SATURN.STVMAJR ON STVMAJR_CODE = SGBSTDN_MAJR_CODE_1
             INNER JOIN SATURN.SHRTCKN SHRTCKN
                 ON SHRTCKN_PIDM = SGBSTDN_PIDM AND SHRTCKN_TERM_CODE = SGBSTDN_TERM_CODE_EFF
             INNER JOIN SATURN.SHRTCKG A
                 ON     SHRTCKG_PIDM = SHRTCKN_PIDM
                    AND SHRTCKG_TERM_CODE = SHRTCKN_TERM_CODE
                    AND SHRTCKG_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
             INNER JOIN SATURN.SHRTCKL
                 ON     SHRTCKL_PIDM = SHRTCKN_PIDM
                    AND SHRTCKL_TERM_CODE = SHRTCKN_TERM_CODE
                    AND SHRTCKL_TCKN_SEQ_NO = SHRTCKN_SEQ_NO
             INNER JOIN SATURN.SHRGRDE
                 ON     SHRTCKL_LEVL_CODE = SHRGRDE_LEVL_CODE
                    AND SHRTCKG_GRDE_CODE_FINAL = SHRGRDE_CODE
                    AND SHRGRDE_TERM_CODE_EFFECTIVE <= SGBSTDN_TERM_CODE_EFF
       WHERE SHRTCKL_PRIMARY_LEVL_IND = 'Y'
    GROUP BY SGBSTDN_PIDM,
             SGBSTDN_MAJR_CODE_1,
             STVMAJR_DESC,
             SHRTCKN_TERM_CODE,
             SHRTCKN_SUBJ_CODE,
             SHRTCKN_CRSE_NUMB,
             SHRTCKN_LONG_COURSE_TITLE,
             SHRTCKN_CRSE_TITLE
      HAVING MAX (SHRTCKG_GRDE_CODE_FINAL) KEEP (DENSE_RANK LAST ORDER BY SHRTCKG_SEQ_NO) NOT IN
                 ('TC', 'DEL', 'DNR');
