-- INPROG_CRSE_LIST: view of in progress courses per student

CREATE OR REPLACE FORCE VIEW GG_OCAS_SYNC.INPROG_CRSE_LIST
(
    PIDM,
    MAJOR,
    MAJOR_DESC,
    TERM_CODE,
    SUBJ_CODE,
    CRSE_NUMB,
    COURSE_TITLE,
    CREDITS,
    LEVEL_CODE
)
AS
    SELECT SFRSTCR_PIDM,
           SGBSTDN_MAJR_CODE_1,
           STVMAJR_DESC,
           SFRSTCR_TERM_CODE,
           SSBSECT_SUBJ_CODE,
           SSBSECT_CRSE_NUMB,
           NVL (SSBSECT_CRSE_TITLE, 'Not Available'),
           NVL (SSBSECT_CREDIT_HRS, 0),
           '00'
      FROM SATURN.SGBSTDN
           INNER JOIN SATURN.SFRSTCR
               ON SFRSTCR_PIDM = SGBSTDN_PIDM AND SGBSTDN_TERM_CODE_EFF = SFRSTCR_TERM_CODE
           INNER JOIN SATURN.SSBSECT
               ON SFRSTCR_CRN = SSBSECT_CRN AND SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE
           INNER JOIN SATURN.STVMAJR SB ON STVMAJR_CODE = SGBSTDN_MAJR_CODE_1
           LEFT JOIN SATURN.SHRTCKN
               ON     SHRTCKN_PIDM = SFRSTCR_PIDM
                  AND SHRTCKN_TERM_CODE = SFRSTCR_TERM_CODE
                  AND SHRTCKN_SUBJ_CODE = SSBSECT_SUBJ_CODE
                  AND SHRTCKN_CRSE_NUMB = SSBSECT_CRSE_NUMB
     WHERE     SFRSTCR_RSTS_CODE IN ('RE', 'RW')
           AND SSBSECT_GRADABLE_IND = 'Y'
           AND SHRTCKN_PIDM IS NULL;
