DROP TABLE GROOVY_GRAILS.OCAS_LOG;

-- Create table

CREATE TABLE GROOVY_GRAILS.OCAS_LOG
(
    ID NUMBER NOT NULL,
    VERSION NUMBER NOT NULL,
    REQUEST_TRACKING_ID VARCHAR2 (35) NOT NULL,
    CREATION_DATE DATE NOT NULL,
    MESSAGE VARCHAR2 (1000) NOT NULL,
    PRIMARY KEY (ID) ENABLE VALIDATE
);

GRANT DELETE, INSERT, SELECT, UPDATE ON GROOVY_GRAILS.OCAS_LOG TO GG_OCAS_SYNC;