DROP TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE CASCADE CONSTRAINTS;

-- Create table

CREATE TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE
(
    ID NUMBER NOT NULL,
    VERSION NUMBER NOT NULL,
    TRANSCRIPT_REQUEST_ID NUMBER NOT NULL,
    SENT NUMBER (1) NOT NULL,
    SEND_TRIGGER VARCHAR2 (30 CHAR) NOT NULL,
    TRIGGER_PARAMETER VARCHAR2 (100 CHAR) NULL,
    PRIMARY KEY (ID) ENABLE VALIDATE,
    FOREIGN KEY
        (TRANSCRIPT_REQUEST_ID)
        REFERENCES GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST (ID) ON DELETE CASCADE
        ENABLE VALIDATE
);

COMMENT ON TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE IS
    'Schedule specification table for transcript requests';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE.TRANSCRIPT_REQUEST_ID IS
    'ID of corresponding request record';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE.SENT IS
    'Whether this schedule has been acted on, and the transcript sent';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE.SEND_TRIGGER IS
    'One of: Now, AfterDegreeAwarded, AfterSpecifiedDate, AfterSpecifiedTerm';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE.TRIGGER_PARAMETER IS
    'Optional additional parameter to specify schedule';

-- Grant/Revoke object privileges 

GRANT DELETE, INSERT, SELECT, UPDATE ON GROOVY_GRAILS.OCAS_TRANSCRIPT_SCHEDULE TO GG_OCAS_SYNC;