DROP TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST CASCADE CONSTRAINTS;

-- Create table

CREATE TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST
(
    ID NUMBER NOT NULL,
    VERSION NUMBER NOT NULL,
    REQUEST_TRACKING_ID VARCHAR2 (35 CHAR) NOT NULL,
    REQUEST_TYPE VARCHAR2 (30 CHAR) NOT NULL,
    REQUEST_DATE DATE NOT NULL,
    RECORD_DATE DATE NOT NULL,
    PIDM NUMBER NULL,
    ERROR_TYPE VARCHAR2 (30 CHAR) NULL,
    OEN VARCHAR2 (30 CHAR) NULL,
    OCAS_APPL_NUMBER VARCHAR2 (30 CHAR) NULL,
    ORIGINAL_XML CLOB NULL,
    RESPONSE_XML CLOB NULL,
    REQUEST_STATUS VARCHAR2 (30 CHAR) NULL,
    RESPONSE_SENT VARCHAR2 (1 CHAR) NULL,
    RESPONSE_STATUS VARCHAR2 (255 CHAR) NULL,
    PRIMARY KEY (ID) ENABLE VALIDATE,
    UNIQUE (REQUEST_TRACKING_ID) ENABLE VALIDATE
);

COMMENT ON TABLE GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST IS 'Incoming XML objects from OCAS API';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST.REQUEST_TRACKING_ID IS
    'Unique key from OCAS XML';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST.REQUEST_TYPE IS
    'Type of communication from OCAS. One of: R - transcript request, T - transcript';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST.ERROR_TYPE IS
    'Type of error, if any, generated on this request';
COMMENT ON COLUMN GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST.RESPONSE_SENT IS
    'Whether the response has been sent to OCAS. One of: Y - yes, N - no';

-- Grant/Revoke object privileges 

GRANT DELETE, INSERT, SELECT, UPDATE ON GROOVY_GRAILS.OCAS_TRANSCRIPT_REQUEST TO GG_OCAS_SYNC;